from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow_Start(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(328, 490, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setCheckable(False)
        self.btn_start.setObjectName("btn_start")
        self.lb_name = QtWidgets.QLabel(self.centralwidget)
        self.lb_name.setGeometry(QtCore.QRect(240, 80, 308, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lb_name.setFont(font)
        self.lb_name.setObjectName("lb_name")
        self.lb_text1 = QtWidgets.QLabel(self.centralwidget)
        self.lb_text1.setEnabled(True)
        self.lb_text1.setGeometry(QtCore.QRect(150, 160, 526, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_text1.setFont(font)
        self.lb_text1.setObjectName("lb__text1")
        self.lb_text2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_text2.setEnabled(True)
        self.lb_text2.setGeometry(QtCore.QRect(80, 270, 662, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_text2.setFont(font)
        self.lb_text2.setObjectName("lb_text2")
        self.lb_text3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_text3.setEnabled(True)
        self.lb_text3.setGeometry(QtCore.QRect(50, 390, 709, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_text3.setFont(font)
        self.lb_text3.setObjectName("lb_text3")
        self.lb_in_name = QtWidgets.QLabel(self.centralwidget)
        self.lb_in_name.setEnabled(True)
        self.lb_in_name.setGeometry(QtCore.QRect(80, 190, 202, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_in_name.setFont(font)
        self.lb_in_name.setObjectName("lb_in_name")
        self.lb_in_age = QtWidgets.QLabel(self.centralwidget)
        self.lb_in_age.setEnabled(True)
        self.lb_in_age.setGeometry(QtCore.QRect(80, 260, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_in_age.setFont(font)
        self.lb_in_age.setObjectName("lb_in_age")
        self.lb_in_course = QtWidgets.QLabel(self.centralwidget)
        self.lb_in_course.setEnabled(True)
        self.lb_in_course.setGeometry(QtCore.QRect(80, 330, 227, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_in_course.setFont(font)
        self.lb_in_course.setObjectName("lb_in_course")
        self.le_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_name.setEnabled(True)
        self.le_name.setGeometry(QtCore.QRect(320, 190, 291, 31))
        self.le_name.setObjectName("le_name")
        self.le_age = QtWidgets.QLineEdit(self.centralwidget)
        self.le_age.setEnabled(True)
        self.le_age.setGeometry(QtCore.QRect(320, 260, 291, 31))
        self.le_age.setObjectName("le_age")
        self.le_corse = QtWidgets.QLineEdit(self.centralwidget)
        self.le_corse.setEnabled(True)
        self.le_corse.setGeometry(QtCore.QRect(320, 330, 291, 31))
        self.le_corse.setObjectName("le_corse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UPT"))
        self.btn_start.setText(_translate("MainWindow", "Розпочати"))
        self.lb_name.setText(_translate("MainWindow", "Universal Personal Tutor"))
        self.lb_text1.setText(_translate("MainWindow", "Програма розроблена лише в цілях навчання"))
        self.lb_text2.setText(_translate("MainWindow", "Не потрібна сприймати серйозно все що видає програма"))
        self.lb_text3.setText(_translate("MainWindow", "Всі курси використовувати лише в цілях загального розвитку"))
        self.lb_in_name.setText(_translate("MainWindow", "Введіть Ваше ім\'я"))
        self.lb_in_age.setText(_translate("MainWindow", "Введіть Ваш вік"))
        self.lb_in_course.setText(_translate("MainWindow", "Введіть назву курсу"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Start()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())