name: Python CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install tokenizers separately (optional)
        run: |
          pip install tokenizers --only-binary :all:

      - name: Run Linter (Flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests with unittest
        run: |
          python -m unittest discover

      - name: Run Black (Python Formatter)
        run: |
          pip install black
          black --check .
